version: "3.0"
services:
  elasticsearch2:
    container_name: es-container2
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elastic2
    ports:
      - 9200:9200

  kibana2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container2:9200
    networks:
      - elastic2
    ports:
      - 5603:5601
    depends_on:
      - elasticsearch2

networks:
  elastic2:
    driver: bridge
