version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elastic
    ports:
      - 9200:9200

  kibana:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - elastic
    ports:
      - 5602:5601
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge
